import type { SyncItem } from "./schemas";
import { mergeSyncText } from "./merge-text";
import { sameSyncContent, stableSyncJson, syncEqual } from "./value";

const CONFLICT = Symbol("conflict");
function record(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}
function entityArray(
  value: unknown
): value is (Record<string, unknown> & { id: string })[] {
  return (
    Array.isArray(value) &&
    value.every((entry) => record(entry) && typeof entry.id === "string") &&
    new Set(value.map((entry) => entry.id)).size === value.length
  );
}
function mergeArrays(
  base: unknown[],
  a: unknown[],
  b: unknown[],
  preferredValue: unknown
): unknown {
  if (!entityArray(base) || !entityArray(a) || !entityArray(b))
    return preferredValue;
  const ids = (items: { id: string }[]) => items.map(({ id }) => id);
  const orderConflict =
    !syncEqual(ids(a), ids(b)) &&
    !syncEqual(ids(a), ids(base)) &&
    !syncEqual(ids(b), ids(base));
  if (orderConflict && !entityArray(preferredValue)) return CONFLICT;
  const commonIds = new Set(
    base
      .filter(
        (item) =>
          a.some((v) => v.id === item.id) && b.some((v) => v.id === item.id)
      )
      .map(({ id }) => id)
  );
  const order = (items: { id: string }[]) =>
    ids(items).filter((id) => commonIds.has(id));
  const ao = order(a);
  const bo = order(b);
  const original = order(base);
  if (
    !syncEqual(ao, bo) &&
    !syncEqual(ao, original) &&
    !syncEqual(bo, original) &&
    !entityArray(preferredValue)
  )
    return CONFLICT;
  const preferred =
    orderConflict && entityArray(preferredValue)
      ? preferredValue
      : !syncEqual(bo, original)
        ? b
        : a;
  const allIds = [...new Set([...ids(preferred), ...ids(a), ...ids(b)])];
  const result: unknown[] = [];
  for (const id of allIds) {
    const value = mergeValue(
      base.find((v) => v.id === id),
      a.find((v) => v.id === id),
      b.find((v) => v.id === id),
      entityArray(preferredValue)
        ? preferredValue.find((v) => v.id === id)
        : CONFLICT
    );
    if (value === CONFLICT) return CONFLICT;
    if (value !== undefined) result.push(value);
  }
  return result;
}
function mergeValue(
  base: unknown,
  a: unknown,
  b: unknown,
  preferred: unknown = CONFLICT
): unknown {
  if (syncEqual(a, b) || syncEqual(base, b)) return a;
  if (syncEqual(base, a)) return b;
  if (Array.isArray(base) && Array.isArray(a) && Array.isArray(b))
    return mergeArrays(base, a, b, preferred);
  if (record(base) && record(a) && record(b)) {
    const result: Record<string, unknown> = {};
    for (const key of new Set([
      ...Object.keys(base),
      ...Object.keys(a),
      ...Object.keys(b)
    ])) {
      // These fields are regenerated by the local storage transaction.
      if (["revision", "projectRevision", "updatedAt"].includes(key)) {
        result[key] = a[key];
        continue;
      }
      const value = mergeValue(
        base[key],
        a[key],
        b[key],
        record(preferred) ? preferred[key] : CONFLICT
      );
      if (value === CONFLICT) return CONFLICT;
      if (value !== undefined) result[key] = value;
    }
    return result;
  }
  return preferred;
}
export function mergeSyncItems(
  base: SyncItem | null,
  local: SyncItem | null,
  remote: SyncItem | null,
  resolution?: { preferred: SyncItem | null }
): { item: SyncItem | null; conflicts: string[] } {
  if (sameSyncContent(local, remote) || sameSyncContent(base, remote))
    return { item: local, conflicts: [] };
  if (sameSyncContent(base, local)) return { item: remote, conflicts: [] };
  if (!base || !local || !remote)
    return resolution
      ? { item: resolution.preferred, conflicts: [] }
      : { item: local, conflicts: ["作品"] };
  const title = mergeValue(
    base.title,
    local.title,
    remote.title,
    resolution ? resolution.preferred?.title : CONFLICT
  );
  const conflicts: string[] = title === CONFLICT ? ["作品名称"] : [];
  const files: Record<string, string> = {};
  for (const path of new Set([
    ...Object.keys(base.files),
    ...Object.keys(local.files),
    ...Object.keys(remote.files)
  ])) {
    const original = base.files[path];
    const a = local.files[path];
    const b = remote.files[path];
    let value: unknown = mergeValue(original, a, b);
    if (
      value === CONFLICT &&
      original !== undefined &&
      a !== undefined &&
      b !== undefined
    ) {
      if (path.endsWith(".md"))
        value =
          mergeSyncText(original, a, b) ??
          (resolution ? resolution.preferred?.files[path] : CONFLICT);
      else if (path.endsWith(".json")) {
        const merged = mergeValue(
          JSON.parse(original),
          JSON.parse(a),
          JSON.parse(b),
          resolution?.preferred?.files[path]
            ? JSON.parse(resolution.preferred.files[path])
            : CONFLICT
        );
        value = merged === CONFLICT ? CONFLICT : `${stableSyncJson(merged)}\n`;
      }
    }
    if (value === CONFLICT && resolution)
      value = resolution.preferred?.files[path];
    if (value === CONFLICT) conflicts.push(path);
    else if (typeof value === "string") files[path] = value;
  }
  return {
    item: {
      ...local,
      title: typeof title === "string" ? title : local.title,
      files
    },
    conflicts
  };
}
