const FORBIDDEN_RENDERER_COMMAND_TYPES = new Set<string>([
  "bookIdentity.submitRound",
  "bookIdentity.readContext",
  "bookIdentity.appendRound",
  "bookIdentity.writeCoverAsset",
  "bookIdentity.readCandidate",
  "bookIdentity.resolveCoverAsset",
  "bookIdentity.recordRenderError",
  "conversationExport.prepare",
  "agent.prompt",
  "agent.extras_run",
  "longBookAnalysis.coreSource",
  "longBookDecomposition.coreCreate",
  "longBookDecomposition.coreAccess",
  "longBookDecomposition.query",
  "longBookDecomposition.submitUnit",
  "longBookDecomposition.planTopic",
  "longMaterialPack.core",
  "agent.abort",
  "agent.user_input_response",
  "agent.model_test",
  "agent.model_capacity",
  "catalog.createShortBookAtPath",
  "catalog.createScriptBookAtPath",
  "long.createBookAtPath",
  "long.previewLegacySyncAtPath",
  "long.applyLegacySyncAtPath",
  "long.importPortableAtPath",
  "long.previewContinuationImportAtPath",
  "long.importContinuationAtPath",
  "long.openAtPath",
  "catalog.createLibraryAtPath",
  "catalog.createLibraryGroupAtPath",
  "catalog.openProjectAtPath",
  "catalog.readLibraryPackageSource",
  "catalog.previewLibraryPackageAtPath",
  "catalog.importLibraryPackageAtPath",
  "catalog.installMarketplaceSkillContent"
]);

export function isForbiddenRendererCommand(type: string): boolean {
  return FORBIDDEN_RENDERER_COMMAND_TYPES.has(type);
}
